- gui/src/settingsdialog.cpp
Makes it less terrible to work with on Deck.
> SettingsDialog: Add second tab to avoid scrollbars

- gui/include/streamsession.h
- gui/src/qml/SettingsDialog.qml
- gui/src/settings.cpp
- gui/src/streamsession.cpp
Start dropping frames once the audio queue gets too big.
Also changed default buffer size and allowed range.
Default buffer size is now 3 frames (30 ms = 5760) which should
be reasonably safe value. Lowest accepted value is now 1 frame
(10ms = 1920).
This fixes possible runaway latency.
Closes #137
>  Audio latency bounding

- lib/include/chiaki/videoreceiver.h
- lib/src/videoreceiver.c
- scripts/flatpak/0001-lavc-vaapi_h264-Fixup-invalid-references.patch
- scripts/flatpak/chiaki4deck.yaml
Same logic as H265.
Also added ffmpeg vaapi patch, no more green with H264.
> VideoReceiver: Parse H264 bitstream and skip decoding corrupted frames

- gui/include/settings.h
- gui/src/main.cpp
- gui/src/settings.cpp
Useful for testing, but can also be used to work around some limitations
like no support for registering one console with multiple users or
using different settings for different consoles.
```
chiaki --profile test
```
> Add --profile option for multiple configuration profiles

- lib/src/videoreceiver.c
It would sometimes incorrectly report invalid reference frame -1.
> VideoReceiver: Fix handling references when frame index wraps around

- gui/include/discoverymanager.h
- gui/src/discoverymanager.cpp
- gui/src/qmlbackend.cpp
- lib/include/chiaki/discoveryservice.h
- lib/src/discoveryservice.c
This speeds up local discovery at launch. Also delay manual host discovery to make it less likely for auto connect to pick remote host.
> Discovery delay

- scripts/flatpak/chiaki4deck.yaml
Microphone doesn't work on SteamOS when using newer libpipewire from org.freedesktop.Platform.
> Flatpak: Use older libpipewire and enable pipewire SDL backend

- gui/src/qmlmainwindow.cpp
This is now needed with FIFO otherwise vkQueuePresentKHR may hang on closing window.
> Destroy swapchain on closing window

- lib/src/videoreceiver.c
Before this change, corrupted frame would only be reported after already receiving packets for next frame, resulting in increased latency until console acknowledges corrupted frame and stops using it as reference.
This can sometimes reduce dropped frames for one corrupted frame from three to two.
> VideoReceiver: Flush frame when receiving last unit

- lib/include/chiaki/vl_rbsp.h
- lib/src/congestioncontrol.c
- lib/src/takion.c
Also avoid divison by zero.
This reverts commit 75fa64ad1b5e89569f54d7a9ad8b9bdcc957670b.
> Revert "CongestionControl: Disable reporting packet loss"

- docs/setup/remoteconnection.md
When connecting remotely, based on Wireshark it sends both TCP & UDP to 9295. Only after updating port forwarding to forward both TCP and UDP it started to connect
It seems the 9295 UDP is only used during registration, but anyway, if it is not port-forwarded, then it isn't possible to add the PS5
Although I'm not a 100% sure if all 9295-9297 should be TCP & UDP, but 9295 definitely seems that way.
> Add UDP as needed port-forward

- gui/MacOSXBundleInfo.plist.in
MacOS 14 Sonoma introduced a new [Game Mode](https://support.apple.com/en-us/105118) that prioritizes performance and increases Bluetooth polling rates.
This PR sets the [`LSApplicationCategoryType` key](LSApplicationCategoryType) to the same value [that Moonlight uses](https://github.com/moonlight-stream/moonlight-qt/blob/3d8de56f251ad8ec4a237c1b59091697e8973c3a/app/Info.plist#L34) to enable this feature. This flag only matters on Sonoma, it will be ignored on older versions of MacOS.
This change only affects Macs, this has effect on non-Apple platforms.
> Enable Game Mode in MacOS

- .github/workflows/build-windows.yml
- CMakeLists.txt
- cmake/FindFFMPEG.cmake
- gui/CMakeLists.txt
- lib/src/ctrl.c
- meson.ini
- scripts/windows-vc/gf-complete.patch
- scripts/windows-vc/libplacebo-pc.patch
- vcpkg.json
This PR brings the native Windows MSVC build up to par with the MSYS2 builds. Totally unnecessary, but nice to have for educational purposes.
Everything works as far as I can tell, including both hardware decoders.
Some caveats/notes for future reference:
- The build script now uses vcpkg to automatically bring in most dependencies with a few exceptions: ffmpeg, shaderc, spirv-cross, and libplacebo
- ffmpeg and shaderc are simply much faster and more convenient to just download the prebuilt binaries
- libplacebo must be built from scratch because it doesn't exist in the vcpkg repository and has no prebuilt binaries
- spirv-cross must be built from scratch because libplacebo requires spirv-cross-c-shared when building for d3d11 support and vcpkg only offers the static version
- The meson …
> Refresh Windows MSVC build

- .github/workflows/build-windows.yml
- scripts/windows-vc/libplacebo-pc.patch
- Reduces the patch context for the libplacebo patch so that it doesn't fail when libplacebo's version number changes
- Lock libplacebo to a specific tag like the msys2 build
> Fix libplacebo patch in MSVC build

- .github/workflows/build-windows.yml
- Fixed orphaned submodules when changing tags in libplacebo checkout
- Updated libplacebo tag and Qt version
> Fix libplacebo checkout in build-windows

- lib/src/congestioncontrol.c
assignment to ‘pthread_t’ {aka ‘long unsigned int’} from ‘void *’ makes integer from pointer without a cast.
> lib: Reset thread to 0 instead of NULL to fix Linux build

- gui/src/main.cpp
Currently no SDL application name is set so volume controls on Linux distributions using Pipewire currently display the default of "SDL Application"
Before:
After:
Unfortunately no way to get an icon here without using SDL3, but apparently switching to SDL3 should mean it will just use the .desktop file icon, but it can also be set with a similar hint `SDL_HINT_AUDIO_DEVICE_APP_ICON_NAME`
> Set SDL application name so the application name appears in volume controls

- .github/workflows/build-windows.yml
- vcpkg.json
This PR brings the MSVC build back to working order again by going back to a full proper external Windows FFmpeg build with the [vulkan segfault patch](https://github.com/streetpea/chiaki4deck/blob/main/scripts/flatpak/0001-vulkan-ignore-frames-without-hw-context.patch) applied (currently hosted at [r52/FFmpeg-Builds](https://github.com/r52/FFmpeg-Builds/)), rather than trying to hamfist the patch into the wonky vcpkg build.
The entire [scripts/ffmpeg-port](https://github.com/streetpea/chiaki4deck/tree/main/scripts/ffmpeg-port) folder should be safe to remove with this.
Other changes: 
- Updated Qt to 6.7.1
- Updated vcpkg tag
- Updated libplacebo tag
> Update MSVC build

- gui/include/qmlmainwindow.h
- gui/include/settings.h
- gui/src/qml/SettingsDialog.qml
- gui/src/qmlmainwindow.cpp
- gui/src/settings.cpp
Will monitor the file `pl_render_params.conf` in the Chiaki config directory (~/Library/Preferences for MacOS see https://doc.qt.io/qt-6/qstandardpaths.html for other platforms) for custom rendering settings and apply them to the running stream. For available options see [1], the syntax is simply a set of `key=value` pairs, separated from each other with either whitespace, comma, semicolon, colon or newline characters.
[1] https://libplacebo.org/options/
> gui: Add new 'custom' quality preset for placebo

- .github/workflows/build-macos.yml
This PR replaces the use of FlyCI macOS runners with GitHub ones since FlyCI macOS runners will be discontinued effective Sep 30, 2024. 
[Read more about the discontinuation of the FlyCI macOS runners](https://flyci.net/blog/flyci-discontinue-macos-runners?utm_source=site_link&utm_medium=github&utm_campaign=discontinue-runners).
> Replace FlyCI runners with GitHub runners

- gui/src/streamsession.cpp
- lib/include/chiaki/remote/holepunch.h
- lib/src/remote/holepunch-test.c
- lib/src/remote/holepunch.c
- lib/src/remote/stun.h
- lib/src/session.c
Move initial upnp discover and stun allocation test to before starting the hole punch session with the psn server to prevent timeouts due to these operations taking too long.
> Update holepunch session to prevent timeout.

- gui/include/qmlsettings.h
- gui/include/settings.h
- gui/src/qml/SettingsDialog.qml
- gui/src/qmlbackend.cpp
- gui/src/qmlmainwindow.cpp
- gui/src/qmlsettings.cpp
- gui/src/settings.cpp
> Add ability to set a custom window resolution

- lib/src/session.c
- switch/include/gui.h
- switch/include/host.h
- switch/src/gui.cpp
Initial PR. Will seat down and do some more testing over the week to see how it plays with other scenarios.
However, the basic flow:
- Initiate a connection request
- Receive connection pin request from ctrl
- Deliberately submit a wrong pin
- Receive an incorrect pin notification from ctrl
- Submit correct pin
- Session begins
works.
Upon the right pin being submitted, EnterPinView is popped and PSRemotePlay continues to initiate the stream session.
> ui: added borealis view and associated callbacks for chiaki_event_login_pin_request

- lib/src/session.c
> Increase time waiting for ctrl to start from 5s to 10s as some PlayStations take longer than 5 seconds for control to start

- switch/include/settings.h
- switch/src/gui.cpp
- switch/src/settings.cpp
For the people with dynamic ip, and use chikai over the internet, you can now change it direct in the interface to enter the new ip, without the need to change the .conf file manually or create a new setup with the new ip, just change the alrady registered profile with the new ip and you are done with it till the ISP change your IP again.
> Add option to change ip address direct from switch interface

- scripts/run-podman-build-appimage.sh
The default run-podman-build-appimage script does not work in Fedora as the chiaki build directory does not mount in the container with proper permissions. I am unsure of the root cause though if things were tested on Ubuntu it is possible there are crun vs. runc differences.
This patch fixes the bug by expanding `-v` to `--volume` (to avoid potential cli aliasing problems) and adds the Z option to map selinux contexts appropriately.
> Updated podman --volume option for Fedora compatability.
