- gui/include/avplacebowidget.h
- gui/src/avplacebowidget.cpp
- scripts/flatpak/0001-Vulkan-Don-t-try-to-reuse-old-swapchain.patch
- scripts/flatpak/chiaki4deck.yaml
This seems to be a better solution.
> libplacebo swapchain reuse

- gui/include/psnaccountid.h
- gui/include/psnlogindialog.h
- gui/include/registdialog.h
- gui/src/psnaccountid.cpp
- gui/src/psnlogindialog.cpp
- gui/src/registdialog.cpp
I've removed the mixed std::string and QString and replaced them with just QString. I've also added error catching and logging.
> PSN Profile ID Collection - Error handling and code cleanup

- gui/src/streamsession.cpp
> StreamSession: Use default audio device as fallback 

- gui/CMakeLists.txt
- gui/include/qmlbackend.h
- gui/include/streamsession.h
- gui/include/systemdinhibit.h
- gui/src/qml/StreamView.qml
- gui/src/qmlbackend.cpp
- gui/src/streamsession.cpp
- gui/src/systemdinhibit.cpp
- scripts/flatpak/chiaki4deck.yaml
Stop session before going to sleep and try to reconnect on resume from sleep.
> Reconnect session on resume from sleep

- gui/src/qml/PSNLoginDialog.qml
- gui/src/qmlmainwindow.cpp
- scripts/Dockerfile.qt6
- scripts/build-appimage.sh
- scripts/build-ffmpeg.sh
- scripts/build-libplacebo.sh
- scripts/build-sdl2.sh
- scripts/run-podman-build-appimage.sh
- steamdeck_native/CMakeLists.txt
* fixed VAAPI
* also fixed Vulkan, but SteamOS has old drivers
* fixed haptics
> AppImage update for Qt 6

- scripts/flatpak/chiaki4deck.yaml
- scripts/flatpak/libplacebo-pr238.patch
- scripts/flatpak/libplacebo-pr239.patch
Vulkan video renders correctly now.
> Add libplacebo patches for Vulkan video

- gui/src/qmlmainwindow.cpp
> QmlMainWindow: Toggle fullscreen on mouse double click

- gui/src/qml/PSNLoginDialog.qml
- gui/src/qmlbackend.cpp
> Fix console registration

- .github/workflows/build-macos.yml
> Downgrade MoltenVK and fix running QtWebEngineProcess

- gui/include/streamsession.h
- gui/src/streamsession.cpp
Fixes issue where extra buttons are sent to stream when hiding stream view overlays.
> StreamSession: Only unblock input after all buttons were released

- gui/include/qmlsettings.h
- gui/include/settings.h
- gui/src/qml/SettingsDialog.qml
- gui/src/qmlbackend.cpp
- gui/src/qmlsettings.cpp
- gui/src/settings.cpp
Allows to put console to sleep when Deck sleeps.
> Settings: Add Suspend Action

- .github/workflows/build-macos.yml
@nowrep I hope I did everything right, I have not merged your changes of copying other libraries, etc. Just added a build of arm64 as a second job in that workflow. Hope I did everything right 🤞
> Add Apple Silicon arm64 build

- .github/workflows/build-macos.yml
Trying to add ad-hoc signing to fix issue #196 
cc @nowrep
> Add ad-hoc signing for the arm64 build

- gui/src/qmlmainwindow.cpp
> Use VK_PRESENT_MODE_FIFO_KHR

- gui/src/qmlbackend.cpp
- gui/src/qmlmainwindow.cpp
> Fix setting stretch and zoom when launched with stream command

- gui/src/qml/AutoConnectView.qml
- gui/src/qml/MainView.qml
Mostly a workaround for Deck to trigger display refresh rate change on startup as soon as possible.
> Startup animations

- lib/src/streamconnection.c
Waits to send takion messages until after bang is received.
> Move enable controller and microphone until after bang received

- gui/include/qmlbackend.h
- gui/include/settings.h
- gui/include/streamsession.h
- gui/src/qml/PsnView.qml
- gui/src/qmlbackend.cpp
- gui/src/settings.cpp
- gui/src/streamsession.cpp
- lib/include/chiaki/session.h
- lib/src/ctrl.c
- lib/src/remote/holepunch.c
- lib/src/remote/stun.h
- lib/src/session.c
Adds supports for ps4 to remote connection via remote psn
> Ps4 remote connection via psn

- cmake/FindCURL.cmake
- gui/include/discoverymanager.h
- gui/include/qmlsettings.h
- gui/include/settings.h
- gui/include/streamsession.h
- gui/src/discoverymanager.cpp
- gui/src/qml/SettingsDialog.qml
- gui/src/qmlsettings.cpp
- gui/src/settings.cpp
- gui/src/streamsession.cpp
- lib/include/chiaki/congestioncontrol.h
- lib/include/chiaki/discovery.h
- lib/include/chiaki/discoveryservice.h
- lib/include/chiaki/session.h
- lib/include/chiaki/streamconnection.h
- lib/src/congestioncontrol.c
- lib/src/ctrl.c
- lib/src/discovery.c
- lib/src/regist.c
- lib/src/remote/holepunch.c
- lib/src/remote/stun.h
- lib/src/session.c
- lib/src/streamconnection.c
Should work about 40% of the time given all other methods fail. Other than this I don't believe there is any more that can be done for connections where remote connection via PSN is not getting responses unless proved otherwise via it working in the official app. In fact, this should work (40 % of the time) in cases where the official app would succeed 0% of the time.
> Random Psn Remote Connection via symmetric NAT

- lib/src/remote/holepunch.c
See <https://github.com/miniupnp/miniupnp/blob/miniupnpc_2_2_8/miniupnpc/Changelog.txt>.
> Fix build with miniupnpc 2.2.8

- gui/include/qmlbackend.h
- gui/src/qmlbackend.cpp
- gui/src/qmlmainwindow.cpp
> Disable zero copy if mapping avframe fails

- switch/include/discoverymanager.h
- switch/src/discoverymanager.cpp
- switch/src/gui.cpp
Discovery manager now works. to be further improved with potential PSN lookup for psn id as well as opening webpage
> fix: discovery manager fixes

- lib/src/remote/holepunch.c
> Try once remote connection

- .github/workflows/build-release.yaml
- .github/workflows/build-weekly.yaml
- scripts/build-small-appimage.sh
- scripts/fetch-protoc.sh
> Arm64 appimage

- gui/src/qmlbackend.cpp
> Add assistant button mapping for Google Stadia controller

- gui/chiaking.desktop
This is an attempt to help with grouping categories better. I've send MR like this to other game streaming projects.
> Add additional categories
